name: Tests

on:
  push

jobs:
  build-n-test:
    name: Build and run Tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Dependencies and run lint
        run: ./scripts/test.sh
        